site_name: HLMWadEditor Documentation
site_url: https://example.com/
markdown_extensions:
  - admonition
theme: windmill
extra:
  article_nav_top: false
  article_nav_bottom: false


extra_css: [extra.css]


nav:
  - Welcome: index.md
  - Your First Mod:
    - 0. Introduction: 'Tutorials/tutorial00.md'
    - 1. The .meta Tool: 'Tutorials/tutorial01.md'
  - Tutorials:
      - Gooo: 'Tutorials/tutorial0.md'